version: '3'

services:
  keycloak:
    build:
      context: .
      dockerfile: alpine.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=tryagain
      - KEYCLOAK_PASSWORD=0p3nw0rld
      - DB_VENDOR=postgres
      - DB_ADDR=localhost
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=saynotodream
      - DB_PASSWORD=0p3nw0rld
