version: '3'

services:
  keycloak:
    build:
      context: .
      dockerfile: alpine.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=tryagain
      - KEYCLOAK_PASSWORD=0p3nw0rld
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: saynotodream
      POSTGRES_PASSWORD: 0p3nw0rld
    ports:
      - "5432:5432"
