version: "3.8"

services:
  keycloak:
    build:
      context: .
      dockerfile: alpine.Dockerfile
    container_name: keycloak
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      KEYCLOAK_USER: tryagain
      KEYCLOAK_PASSWORD: 0p3nw0rld
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: saynotodream
      DB_PASSWORD: 0p3nw0rld

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: saynotodream
      POSTGRES_PASSWORD: 0p3nw0rld
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
